services:
  app:
    image: ghcr.io/dlrjswn/community:${IMAGE_TAG:-latest}
    container_name: spring-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    command: >
      sh -c 'exec redis-server --appendonly yes'   # 비밀번호 미사용
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: {}
