name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Check build output
        run: ls -al build/libs

      - name: Create .env file
        run: |
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> .env
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> .env

      - name: Check .env file
        run: cat .env

      - name: ✅ Validate build and env files exist
        run: |
          if [ ! -f build/libs/*.jar ]; then
            echo "❌ JAR file not found!"
            ls -al build/libs
            exit 1
          fi
          if [ ! -f .env ]; then
            echo "❌ .env file not found!"
            ls -al
            exit 1
          fi

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: |
            build/libs/community-0.0.1-SNAPSHOT.jar
            .env
          target: "~/app"

      - name: Remote SSH to EC2 - Run Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/app
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 8080:8080 \
              --env-file .env \
              -v ~/app/*.jar:/app.jar \
              openjdk:17 java -jar /app.jar
